[phases.setup]
nixPkgs = ['nodejs-22_x']

[phases.install]
cmds = ['cd backend && npm install --omit=dev --ignore-scripts --no-package-lock']

[phases.build]
cmds = []

[start]
cmd = 'cd backend && npm start'

